# Generated by Django 4.1.4 on 2023-01-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactuspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-06 17:01:01'),
            preserve_default=False,
        ),
    ]
