# Generated by Django 4.1.5 on 2023-03-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cartbookingmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbookingmodel',
            old_name='date',
            new_name='appointmentdate',
        ),
    ]
