# Generated by Django 4.1.5 on 2023-03-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_date_cartbookingmodel_appointmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbookingmodel',
            old_name='appointmentdate',
            new_name='date',
        ),
    ]
