# Generated by Django 4.2.2 on 2023-06-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_appointmentdate_cartbookingmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbookingmodel',
            old_name='date',
            new_name='bookingdate',
        ),
    ]
