# Generated by Django 4.2.2 on 2023-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_date_cartbookingmodel_bookingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbookingmodel',
            old_name='bookingdate',
            new_name='appointmentdate',
        ),
    ]
