# Generated by Django 4.1.4 on 2023-01-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_contactuspage_date_remove_contactuspage_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermaLogicaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('derma1', models.TextField()),
                ('derma2', models.TextField()),
                ('derma3', models.TextField()),
                ('derma4', models.TextField()),
                ('derma5', models.TextField()),
                ('derma6', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about2',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about3',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about4',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about5',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='about6',
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-11 10:11:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
