# Generated by Django 4.2.2 on 2023-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_bookingdate_cartbookingmodel_appointmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbookingmodel',
            old_name='appointmentdate',
            new_name='date',
        ),
    ]
