# Generated by Django 4.1.4 on 2023-01-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_dermalogicapage_derma7_dermalogicapage_derma8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
        migrations.DeleteModel(
            name='DermaLogicaPage',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
