# Generated by Django 4.1.4 on 2023-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_aboutuspage_delete_dermalogicapage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
