# Generated by Django 4.1.5 on 2023-02-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=15)),
                ('datentime', models.DateTimeField()),
                ('total_payment', models.CharField(max_length=20)),
                ('BookingTime', models.DateTimeField(auto_now_add=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cartitem')),
            ],
        ),
    ]
