# Generated by Django 4.1.5 on 2023-02-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_cartbookingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbookingmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='services',
            field=models.ManyToManyField(to='website.cartitem'),
        ),
    ]
