# Generated by Django 4.1.5 on 2023-02-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_cartbookingmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='username',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
