# Generated by Django 4.1.5 on 2023-02-21 06:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_cartbookingmodel_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbookingmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='json',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
