# Generated by Django 4.1.5 on 2023-02-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_json_cartbookingmodel_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbookingmodel',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
