# Generated by Django 4.1.5 on 2023-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_cartbookingmodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
