# Generated by Django 4.1.4 on 2023-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about1', models.TextField()),
                ('about2', models.TextField()),
                ('about3', models.TextField()),
                ('about4', models.TextField()),
                ('about5', models.TextField()),
                ('about6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DermaLogicaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('derma1', models.TextField()),
                ('derma2', models.TextField()),
                ('derma3', models.TextField()),
                ('derma4', models.TextField()),
                ('derma5', models.TextField()),
                ('derma6', models.TextField()),
                ('derma7', models.TextField()),
                ('derma8', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('home1', models.TextField()),
                ('home2', models.TextField()),
                ('home3', models.TextField()),
                ('home4', models.TextField()),
            ],
        ),
    ]
