# Generated by Django 4.1.4 on 2023-01-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_dermalogicapage_dermahead1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermalogicapage',
            name='dermahead8',
        ),
    ]
