# Generated by Django 4.1.4 on 2023-01-18 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_nailpage_alter_waxingpage_derma1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailpage',
            name='derma3',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
