# Generated by Django 4.1.4 on 2023-01-18 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_alter_nailpage_derma3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailpage',
            name='derma2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
