# Generated by Django 4.1.4 on 2023-01-18 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_makeuppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuppage',
            name='derma5',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
