# Generated by Django 4.1.4 on 2023-01-18 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_electropage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electropage',
            name='derma1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
