# Generated by Django 4.1.4 on 2023-01-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_manpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpage',
            name='derma7',
        ),
    ]
