# Generated by Django 4.1.4 on 2023-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0019_giftpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
