# Generated by Django 4.1.5 on 2023-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_alter_giftpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home4',
        ),
        migrations.AddField(
            model_name='homepage',
            name='head1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='head2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='head3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='head4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
