# Generated by Django 4.1.5 on 2023-03-07 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0021_remove_homepage_home4_homepage_head1_homepage_head2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home3',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
