# Generated by Django 4.2.2 on 2023-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0022_alter_homepage_home3'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
