# Generated by Django 4.1.4 on 2023-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_bookingmodel_datentime_bookingmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
