# Generated by Django 4.1.4 on 2023-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_bookingmodel_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='name',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
