# Generated by Django 4.1.4 on 2023-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_bookingmodel_phone_alter_bookingmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='total_payment',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
