# Generated by Django 4.1.4 on 2023-01-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_bookingmodel_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='hidname',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
