# Generated by Django 4.1.4 on 2023-01-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_bookingmodel_hidname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='hidname',
        ),
    ]
