# Generated by Django 4.1.4 on 2023-01-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_remove_bookingmodel_hidname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
